//
//  CoursePlannerViewModel.swift
//  CoursePlanner
//
//  Created by Rickey Chiu on 5/29/23.
//

import SwiftUI

let idToCourse: [CourseIdentifier: Course] = [
    
    //ADD
    "0000": Course(name: "+", id: "0000", description: "", recommended: [], department: .zero, type: .other, grade: [0,1,2,3]),
    
    //ENGLISH
    "1010P": Course(name: "Lit & Writing", id: "1010P", description: "This course integrates the study of literature with instruction in the writing process. Students will explore the ideas and issues of literature while improving their writing, speaking, listening, thinking and language skills. Materials include poetry and prose, fiction and non-fiction.", recommended: [], department: Department.english, type: CourseType.standard, grade: [0]),
    "1013P": Course(name: "Lit & Writing (EL)", id: "1013P", description: "This ELD course integrates the study of literature with instruction in the writing process. Students will explore the ideas and issues of literature while improving their writing, speaking, listening, thinking and language skills. Materials include poetry and prose, fiction and non-fiction.", recommended: [], department: Department.english, type: CourseType.standard, grade: [0, 1]),
    "1020P": Course(name: "World Lit", id: "1020P", description: "Using works of world literature, the student will explore themes of human experience and inquiry. The literature will include novels, plays, stories and poetry by historical and contemporary authors from around the world. This literature-based program provides instruction and experiences for students to build their listening, speaking, reading, writing and thinking skills.", recommended: [], department: Department.english, type: CourseType.standard, grade: [1]),
    "1023P": Course(name: "World Lit (EL)", id: "1023P", description: "Using works of world literature, the student will explore themes of human experience and inquiry. The literature will include novels, plays, stories and poetry by historical and contemporary authors from around the world. This ELD literature-based program provides instruction and experiences for students to build their listening, speaking, reading, writing and thinking skills.", recommended: [], department: Department.english, type: CourseType.standard, grade: [1, 2]),
    "1130P": Course(name: "American Lit", id: "1130P", description: "This course provides rigorous and challenging experiences for the student in the areas of critical reading, critical thinking, effective discussion, essay test-taking, expository writing and research. The core of the curriculum is a chronological or thematic study of American literature, its literary periods and major writings. Outside reading focuses on broader philosophical ideas, encouraging wider reading including classics by American authors.", recommended: [], department: Department.english, type: CourseType.standard, grade: [2]),
    "1133P": Course(name: "American Lit (EL)", id: "1133P", description: "This ELD course provides rigorous and challenging experiences for the student in the areas of critical reading, critical thinking, effective discussion, essay test-taking, expository writing and research. The core of the curriculum is a chronological or thematic study of American literature, its literary periods and major writings. Outside reading focuses on broader philosophical ideas, encouraging wider reading including classics by American authors.", recommended: [], department: Department.english, type: CourseType.standard, grade: [2, 3]),
    "1190AP": Course(name: "AP Eng Lang & Comp", id: "1190AP", description: "Recommended: Grade of “B” or better in previous English courses. The AP course in English Language and Composition engages students in becoming skilled readers of prose written in a variety of periods, disciplines, and rhetorical contexts, and in becoming skilled writers who compose for a variety of purposes. The course also shows how generic conventions and the resources of language contribute to effectiveness in writing This course uses a survey of American literature and writing from the beginning of the country to modern times with which to frame the studies of language and composition. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment.", recommended: ["1010P", "1020P"], department: Department.english, type: CourseType.ap, grade: [2]),
    "1260P": Course(name: "Story & Style", id: "1260P", description: "This course presents students with new ways to view multiple literary genres including, but not limited to, drama, speech, multimedia text, expository text, and the novel. Students will analyze and evaluate their world through the lenses of the texts they read and write about during this course. They will become more critical consumers of the written and spoken word through an ongoing examination of how an author manipulates a text's structure and syntax to illustrate a point. Students will explore themes of personal reflection and the human condition through expository and literary essays, creative non-fiction, persuasive speeches, and class discussions. Students will complete a senior thesis, which involves extensive, in-depth research on an individual topic and interaction with members of the community.", recommended: [], department: Department.english, type: CourseType.standard, grade: [3]),
    "1410AP": Course(name: "AP Eng Lit & Comp", id: "1410AP", description: "Recommended: Grade of “B” or better in previous English courses and teacher recommendation. This Advanced Placement English course in Literature and Composition engages students in the careful reading and critical analysis of literature. Through the close reading of selected texts, students deepen their understanding of the ways writers use language to provide both meaning and pleasure for their readers. As they read, students consider a work’s structure, style and themes, as well as smaller-scale elements, such as the use of figurative language, imagery, symbolism and tone. The course includes intensive study of representative works from various genres and periods, concentrating on selections that do not yield all of their pleasures of thought and feeling the first time through. Students will read deliberately and thoroughly, taking time to understand a work’s complexity in order to absorb its richness of meaning and to analyze how that meaning is embodied in literary form. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Programresult of “Conditionally Ready” on the 11th grade Smarter Balanced assessment.", recommended: ["1130P", "1190AP"], department: Department.english, type: CourseType.ap, grade: [3]),
    
    "1360P": Course(name: "Journalism/EPIC", id: "1360P", description: "An elective class for students who produce the student newspaper, assuming full responsibility for its development, production and marketing while meeting similar challenges to those experienced by the professional field. The curriculum also provides an opportunity to create a personal reading program representing the research focused on societal forces, trends and issues (application and interview required.)", recommended: [], department: Department.english, type: CourseType.standard, grade: [1, 2, 3]),
    
    "1450": Course(name: "Eng. Lang Dev 2", id: "1450", description: "Recommended: Assessment. This course is designed for students who already have a foundational knowledge of English in academic and communicative vocabulary, sentence structure, reading of non-fictional and fictional texts, and writing. Through quality interactive instruction and activities, students will continue to build cognitive academic language proficiency in all four skill areas. Texts will be of greater length and complexity. Students will be introduced to additional expository and narrative writing genres, including persuasive, research and biographical essays.", recommended: [], department: Department.english, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "1460P": Course(name: "Eng. Lang Dev 3", id: "1460P", description: "This course is designed for advanced learners of English as an additional language. Students acquire sophisticated academic and communicative vocabulary, sentence structure, reading of non-fictional and fictional texts, and writing. Students read non-fictional and fictional texts of demanding length and complexity in various genres to prepare them for advanced mainstream English and courses in other content areas. Throug quality interactive instruction and activities, a print-rich environment, and public speaking experiences, students will continue to solidify cognitive academic language proficiency in all four skill areas. Students will be introduced to additional expository and narrative writing genres, including full research reports and reflective essays.", recommended: [], department: Department.english, type: CourseType.standard, grade: [0, 1, 2, 3]),
    
    //SOCIAL STUDIES
    "1620P": Course(name: "World History", id: "1620P", description: "Recommended: None. In this course, students examine major turning points in the shaping of the modern world and the rise of Democratic ideas from the late eighteenth century to the present. The year begins with an introduction to current world issues and then continues with a focus on the expansion of the West and the growing interdependence of people and cultures throughout the world including Asia, Africa, and the Middle East.", recommended: [], department: Department.social, type: CourseType.standard, grade: [1]),
    "1623P": Course(name: "World History (EL)", id: "1623P", description: "Recommended: None. In this course, ELD students examine major turning points in the shaping of the modern world and the rise of Democratic ideas from the late eighteenth century to the present. The year begins with an introduction to current world issues and then continues with a focus on the expansion of the West and the growing interdependence of people and cultures throughout the world including Asia, Africa, and the Middle East.", recommended: [], department: Department.social, type: CourseType.standard, grade: [1]),
    "1730P": Course(name: "U.S. History", id: "1730P", description: "Recommended: None. In this course, students study the History of the United States in the twentieth century. The year begins with a review of U.S. History prior to the 20th Century. After the review unit, this course will study: America at the turn of the Century, United States as a world power, the 1920’s, the Great Depression and New Deal, United States in World War II and the post-war period, U.S. foreign policy since World War II, the Civil Rights movement, and the Unites States in contemporary society.", recommended: [], department: Department.social, type: CourseType.standard, grade: [2]),
    "1750AP": Course(name: "AP U.S. History", id: "1750AP", description: "Recommended: Students should have earned a “B” or better in their previous history class and have strong writing skills. This survey course gives students a thorough grounding in facts, and goes on to examine the significance of facts, their contexts, their causes and results. This course is designed to provide students with the analytic skills and factual knowledge necessary to deal critically with the problems and material in United States history. Students learn how to read historical material analytically and critically, to weigh historical evidence and interpretations and to arrive at conclusions on the basis of facts. Students should expect a steady and heavy load of reading from the textbook, in addition to Document Based and Free Response essays that put particular demands on historical knowledge and the ability to make and prove a historical argument. Unlike the mainstream US History course, where there is single focus on the US in the 20th Century, AP US History covers the entire scope of our history, from the Amerindian settlements to contemporary American issues. The course makes demands similar to those found in introductory college courses and prepares students for success on the AP US History test held in early May.", recommended: [], department: Department.social, type: CourseType.ap, grade: [2]),
    "1835P": Course(name: "Economics (1/2)", id: "1835P", description: "Recommended: None. The course covers economic principles such as production, supply and demand, profits, distribution of goods, competition, money and banking, government monetary and fiscal policies, credit insurance, securities market and comparative economic systems.", recommended: [], department: Department.social, type: CourseType.standard, grade: [3]),
    "1845P": Course(name: "U.S. Government (2/2)", id: "1845P", description: "Recommended: None. The goals of this course are to give an understanding of democratic processes and an awareness of the values and social framework that support them. Major units in the course are federal government, state government, political parties and elections and selected issues of government in the United States.", recommended: [], department: Department.social, type: CourseType.standard, grade: [3]),
    "1855AP": Course(name: "AP U.S. Gov/Politics (2/2)", id: "1855AP", description: "Recommended: Students should have earned a “B” or better in their previous history class and have strong writing skills. The advanced placement course in government parallels an introductory college course in political science. The course is designed to give students a thorough understanding of and critical perspective on the system of US government politics, policy and practices. Instruction emphasizes understanding course content by way of in-depth research and analysis. Furthermore, students will apply their understanding of the subject matter to both historical and current political events and analyze their impact on American society. AP US Government and Politics is a tightly structured, highly demanding, fast-paced college-level course in which students study a year’s amount of curriculum in only one semester. Students will be required to read the college-level textbook and supplemental readings. Expository writing will be required. Ideally, this course is really for those students who are specifically interested in government and politics.", recommended: [], department: Department.social, type: CourseType.ap, grade: [3]),
    
    //PE
    "2510": Course(name: "P.E. 9", id: "2510", description: "Recommended: None. A basic course required of all freshmen, which includes instruction in beginning and intermediate skills, basic rules, history and etiquette in a variety of sports. To complete the program, a student must complete the objectives of an activity in each of the following areas: Individual—an activity in which the student performs without the need of another person; Dual—an activity in which a student competes against another student; Team—an activity in which a group of students compete against another group of students; Rhythmic—an activity in which movement is coordinated with music or a rhythmic beat; Aquatic—an activity which covers the basic skills of swimming; Wellness—fundamentals of good health practices are incorporated in activities.", recommended: [], department: Department.pe, type: CourseType.other, grade: [0]),
    "2530": Course(name: "P.E. 10-12", id: "2530", description: "Recommended: PE 9. The PE 10 elective program is designed to allow choice in the selection of physical education activities. Emphasis is placed on refining basic skill and participation. The activities typically offered may include: aerobics, aquatics, basketball, badminton, body development, dance, flag football, game management, golf, gymnastics, pickleball, recreational games, soccer, softball, tennis, track, ultimate Frisbee, volleyball, weight training, wrestling.", recommended: ["2510"], department: Department.pe, type: CourseType.other, grade: [1, 2, 3]),
    "2720": Course(name: "P.E. Racquet Sports", id: "2720", description: "Recommended: PE 9. This course is designed for students interested in developing skills in the various racquet sports and physical conditioning: tennis, pickle ball and badminton. Emphasis is placed on refining skills, strategy and competitive doubles and singles play.", recommended: ["2510"], department: Department.pe, type: CourseType.other, grade: [1, 2, 3]),
    "2740": Course(name: "P.E. Weight Training", id: "2740", description: "Recommended: PE 9. This course is designed for those students interested in developing body strength for advanced sports skills. Students will engage in weightlifting, cardiovascular conditioning and flexibility exercises. Students will utilize both free weights and weight machines.", recommended: ["2510"], department: Department.pe, type: CourseType.other, grade: [1, 2, 3]),
    "2780": Course(name: "P.E. Total Fitness", id: "2780", description: "Recommended: PE 9. The course emphasizes aerobic activity with elements of all five of the components of fitness: cardiovascular endurance, muscular strength, muscular endurance, flexibility and body composition. This course is set to prepare students for a life of fitness after high school. Knowledge of anatomy and physiology will be introduced. Individual students will be assessed primarily on their own personal fitness level and student personal PE folders will be maintained.", recommended: ["2510"], department: Department.pe, type: CourseType.other, grade: [1, 2, 3]),
    "2590": Course(name: "P.E. Athletics*", id: "2590", description: "Required: Student must be a member of an interscholastic athletic squad and MUST complete the PE Sport Competitive Sports Participation Agreement. This is an elective course, limited to students who are members of interscholastic athletic squads, spirit, drill and auxiliary teams. 10th grade students who wish to earn their PE credit through a team rather than a regular PE class MUST complete PE Sport Competitive Sports Participation Agreement and attend a mandatory meeting during the course selection season – prior to enrolling in PE Athletics 9th grade students may earn 5 elective credits per Sport, but will not be given PE credit for participation on an athletic team.", recommended: [], department: Department.pe, type: CourseType.other, grade: [1, 2, 3]),
    
    //ART
    
    "6110P": Course(name: "Art 1", id: "6110P", description: "Recommended: None. This is an introductory course that provides the student an opportunity to explore the elements of design such as line, shape, color, form, value and texture through the use of various media including drawing, painting printing making and collage. Basic visual literacy and visual communication skills will be instructed. A basic survey of art history will be covered.", recommended: [], department: Department.art, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "6120P": Course(name: "Art 2", id: "6120P", description: "Recommended: C or better in Art 1. This is an intermediary art course. Further refinement of drawing and painting skills will be the primary focus, but various art making practices and new media may be introduced such as pastel painting, colored pencil, mixed media, scratchboard, and mask painting. Visual literacy and visual communication skills will be further developed. Historical and contemporary topics will be evident in student work and /or through class discussion.", recommended: ["6110P"], department: Department.art, type: CourseType.standard, grade: [1, 2, 3]),
    "6130P": Course(name: "Art 3", id: "6130P", description: "Recommended: C or better in Art 2. This is an advanced level course focused around a specialized area of art and / or around the exploration of a variety of media and techniques. In addition, Students will be directed in developing their own creative voice and work for a portfolio. Advanced visual literacy and visual communication skills will be further developed. Historical and contemporary topics will be evident in student work and /or through class discussion.", recommended: ["6120P"], department: Department.art, type: CourseType.standard, grade: [2, 3]),
    
    "6210P": Course(name: "3D Sculpture & Design 1", id: "6210P", description: "Recommended: None. This is a basic design course for students primarily interested in three-dimensional materials. Design for both aesthetic and functional objects is emphasized. Whether the objects are utilitarian or aesthetic, a regard for quality of workmanship and design is stressed. Not only do students explore a variety of media such as clay, leather, wood, metal, enamels, etc., they also gain an appreciation for handcrafted articles as they reflect our past and present culture.", recommended: [], department: Department.art, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "6220P": Course(name: "3D Sculpture & Design 2", id: "6220P", description: "Recommended: C or better in 3-D Design 1. Students will further their knowledge and appreciation of design with more depth and complexity, as well as increase their skills in handling materials and tools. Various new media are introduced and experimentation and individualized instruction are encouraged. The skills learned are useful for future employment in an art-oriented occupation, for communicating ideas and preparing for further education.", recommended: ["6210P"], department: Department.art, type: CourseType.standard, grade: [1, 2, 3]),
    "6230P": Course(name: "3D Sculpture & Design 3", id: "6230P", description: "Recommended: C or better in 3-D Design 2. For the advanced design student who has professional or vocational goals in a particular area. The student will develop a high level of skill in a specific medium. The student will be encouraged to make contact with professional people in their specific fields and research techniques in the medium, culminating with a brief report. Specific projects will result from a student/teacher conference that will outline the projects to be completed each semester.", recommended: ["6220P"], department: Department.art, type: CourseType.standard, grade: [2, 3]),
    
    "6360P": Course(name: "Cermaics 1", id: "6360P", description: "Recommended: None. This is an introductory art course centered on developing hand-building techniquessuch as pinch, slab and coil. Introductory work on the potter’s wheel may be explored. Techniques in underglazing, inlay and carving will be explored. In addition, a variety of glazing techniques will be demonstrated.", recommended: [], department: Department.art, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "6370P": Course(name: "Cermaics 2", id: "6370P", description: "Recommended: C or better in Ceramics 1. The student will design and produce a variety of forms that utilize hand-building methods and wheel-throwing techniques. Advanced surface decoration will be explored such as inlay, texture and stamping.", recommended: ["6360P"], department: Department.art, type: CourseType.standard, grade: [1, 2, 3]),
    "6380P": Course(name: "Cermaics 3", id: "6380P", description: "Recommended: C or better in Ceramics 2. The student will continue refinement in basic hand-building and potter’s wheel techniques. Exploration in decorating methods and self-directed projects will be developed.", recommended: ["6370P"], department: Department.art, type: CourseType.standard, grade: [1, 2, 3]),
    
    "6450AP": Course(name: "AP 2D Art & Design", id: "6450AP", description: "Recommended: B or better in Art 2, or evaluation of student portfolio. This course is designed for the student who is seriously interested in art as a potential college major or career. The curriculum will include the development of a portfolio that may be used for college admission and submitted to the College Board for the AP Examination. Students will be required to complete homework assignments outside of class and to maintain a sketchbook. Only students enrolled in the AP Art course will be allowed to register and submit an AP Portfolio in May.", recommended: ["6120P"], department: Department.art, type: CourseType.ap, grade: [2, 3]),
    "7790": Course(name: "Studio Art", id: "7790", description: "Recommended: Level 1 Art/ Ceramics/ 3-Design/Photography. Students will focus on building their personal portfolio and gain entrepreneurial skills required to become a successful artist. Advanced Visual Communications coordinates 2-D and 3-D studio work and cultural studies together with an emphasis on careers in the art field. Selected cultures of Meso-American, Italian, German, French, Middle Eastern and Asian art will be introduced and students will produce projects that relate to each unique culture to be included in their portfolio. Language and cultural studies will be taught on a daily basis so as to appreciate historical and cultural differences. The art elements and principles of design composition serve as a foundation for each unit covered and attention will be given to visual studio work. Students will gain knowledge and an appreciation for various art forms and entrepreneurship skills that will lead to a successful career in the visual communications field. This course can be taken for credit and grade in both junior and senior year. NOTE: This course does not prepare students for the AP Studio Art: Drawing exam", recommended: ["6110P", "6360P", "6210P", "7670P"], department: Department.art, type: CourseType.standard, grade: [2, 3]),
    "7670P": Course(name: "Photography & Design", id: "7670P", description: "Photography and Design is a yearlong course that begins with understanding the basic operations and functions of a digital single lens reflex camera and the manipulation of its settings to achieve a specific result. Students will learn about photographic elements of art and principles of design, composition, and lighting. They will explore the history of photography, learning about important innovators in the field, and relevance Lynbrook High School Guidance Planning and Course Selection Guide Page | 27 within diverse cultural contexts. Students will write and speak about aesthetic, technical and expressive qualities in a photograph, learning to critique their own and others work. Students learn image techniques and digital manipulation using Adobe Photoshop and Lightroom, teaching them how to archive, organize and optimize their photographs for print or web purposes. Students will learn how to creatively alter digital images as well as critically analyze the use of visual media as a means of communication in our society today. They will be provided a greater level of autonomy, expected to pursue their own interests and develop an individual voice. Beginning second semester, students will explore the relationship between photography, graphic design and advertising/media applications. Students will explore visual communication that is both directed by industry needs (advertising/graphic design) and personal creative drives (photography as fine art).", recommended: [], department: Department.art, type: CourseType.standard, grade: [1, 2, 3]),
    
    //SCIENCE
    "3110P": Course(name: "Biology", id: "3110P", description: "Recommended: None. Biology is an introductory laboratory course based on the Next Generation Science Standards that includes the following core ideas: From Molecules to Organisms: Structures and Processes; Ecosystems: Interactions, Energy, and Dynamics; Heredity: Inheritance and Variation of Traits; and Biological Evolution: Unity and Diversity. Students will explore and deepen their understanding of these core ideas through scientific inquiry. In the process, they will learn to think and act like scientists by using science practices and cross-cutting concepts that they can apply in subsequent science courses. As part of the California Healthy Youth Act, students will engage in a comprehensive sexual health education unit that will prepare them to make informed and healthy choices.", recommended: [], department: Department.science, type: CourseType.standard, grade: [0]),
    "3113P": Course(name: "Biology EL", id: "3113P", description: "Recommended: None. ELD Biology is an introductory laboratory course based on the Next Generation Science Standards that includes the following core ideas: From Molecules to Organisms: Structures and Processes; Ecosystems: Interactions, Energy, and Dynamics; Heredity: Inheritance and Variation of Traits; and Biological Evolution: Unity and Diversity. Students will explore and deepen their understanding of these core ideas through scientific inquiry. In the process, they will learn to think and act like scientists by using science practices and cross-cutting concepts that they can apply in subsequent science courses. As part of the California Healthy Youth Act, students will engage in a comprehensive sexual health education unit that will prepare them to make informed and healthy choices.", recommended: [], department: Department.science, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "3120AP": Course(name: "AP Biology", id: "3120P", description: "Recommended: Biology and Chemistry. AP Biology is the equivalent of a two-semester college introductory biology course that focuses on enduring conceptual understandings and the content that support them. This course is based on eight units including: Chemistry of Life, Cell Structure and Function, Cellular Energetics, Cell Communication and Cell Cycle, Heredity, Gene Expression and Regulation, Natural Selection, and Ecology. While delving deeply into these foundational biology concepts, students will develop their inquiry and reasoning skills by designing experiments, analyzing data, and justifying arguments using evidence.", recommended: ["3110P", "3610P", "3620H"], department: Department.science, type: CourseType.ap, grade: [2, 3]),
    "3130P": Course(name: "Physiology", id: "3130P", description: "Recommended: Biology and Chemistry. This is a laboratory course investigating the functional and interdependent phenomena of the human body, its systems, and the maintenance of homeostasis. Studies include anatomical structure and physiological function for the development, performance, and coordination of internal and external activities of the human body. Dissections, observations of organs, and practice with models serve as an anchor for understanding these human systems.", recommended: ["3110P", "3610P", "3620H"], department: Department.science, type: CourseType.standard, grade: [2, 3]),
    "3610P": Course(name: "Chemistry", id: "3610P", description: "Recommended: Biology and Algebra 1 (can be concurrent). Chemistry is a laboratory course based on the Next Generation Science Standards. Students will explore and deepen their understanding of Earth’s systems and humans’ relationships with the Earth through the lens of chemistry, which include the following core ideas: structures and properties of matter, chemical reactions, and the energy and forces that drive these interactions. Students will continue to grow in their ability to learn, to think, and to act like scientists, preparing them to make informed decisions about important science-related issues in our society and the world. Emphasis is placed on conceptual understanding of ideas, and students are expected to use algebra to explain these ideas.", recommended: ["3110P"], department: Department.science, type: CourseType.standard, grade: [1, 2, 3]),
    "3620H": Course(name: "Chemistry - Honors", id: "3620H", description: "Recommended: Biology and Geometry (can be concurrent). Chemistry Honors is a laboratory course based on the Next Generation Science Standards. Students will explore and deepen their understanding of Earth’s systems and humans’ relationships with the Earth through the lens of chemistry, which includes the following core ideas: structures and properties of matter, chemical reactions, and the energy and forces that drive these interactions. Students will continue to grow in their ability to learn, to think and to act like scientists, preparing them to make informed decisions about important science-related issues in our society and the world. The honors course incorporates an increased application of mathematical reasoning to explain chemical phenomena, a rigorous application of the concepts, and more intensive pacing.", recommended: [], department: Department.science, type: CourseType.honors, grade: [1, 2, 3]),
    "3630AP": Course(name: "AP Chemistry", id: "3630AP", description: "Recommended: Chemistry Honors and Algebra 2. AP Chemistry is the equivalent of a two-semester college introductory chemistry course. The course is organized around six big ideas that students will come to understand: atomic structure, chemical and physical properties of matter, chemical reactions, reaction kinetics, thermodynamics, and chemical equilibrium. Emphasis is placed on laboratory experimentation, problem solving and quantitative understanding of complex chemical phenomena. Students taking this course should have a successful background in mathematics and basic chemistry.", recommended: ["3620H"], department: Department.science, type: CourseType.ap, grade: [2, 3]),
    "3710P": Course(name: "Physics", id: "3710P", description: "Recommended: Biology and Algebra 1. Physics is a laboratory course based on the Next Generation Science Standards. Students will explore and deepen their understanding of the universe and humans’ relationships with the Earth through the lens of physics, which includes the following core ideas: energy, matter, forces, time, and space. Students will continue to grow in their ability to learn, to think, and to act like scientists, preparing them to make informed decisions about important science-related issues in our society and the world. Emphasis is placed on conceptual, rather than the mathematical, understanding to explain natural phenomena.", recommended: ["3110P"], department: Department.science, type: CourseType.standard, grade: [1, 2, 3]),
    "3720H": Course(name: "Physics - Honors", id: "3720H", description: "Recommended: Biology and Algebra 2 (can be concurrent). Physics Honors is a laboratory course based on the Next Generation Science Standards. Students will explore and deepen their understanding of the universe and humans’ relationships with the Earth through the lens of physics, which includes the following core ideas: energy, matter, forces, time, and space. Students will continue to grow in their ability to learn, to think, and to act like scientists, preparing them to make informed decisions about important science-related issues in our society and the world. The honors course incorporates an increased application of mathematical reasoning to explain physical phenomena, a rigorous application of the concepts, and more intensive pacing.", recommended: ["3110P"], department: Department.science, type: CourseType.honors, grade: [1, 2, 3]),
    "3730AP": Course(name: "AP Physics C: Mech", id: "3730AP", description: "Recommended: Pre-Calculus Honors and Physics Honors/AP Physics 1. This course is the equivalent of a one-semester, calculus-based, college physics course for science or engineering majors. Students will deepen their laboratory experimentation, problem solving, and quantitative understanding of physics. Students taking this course should have a successful background in mathematics and algebra-based physics.", recommended: ["2420H", "3720H"], department: Department.science, type: CourseType.ap, grade: [2, 3]),
    "3850P": Course(name: "Science & Society", id: "3850P", description: "Recommended: Biology. This course is a Project Based Learning (PBL) course where students work on a variety of projects that connect important scientific concepts within current societal issues. As an interdisciplinary science class, the focus is on developing critical thinking and scientific literacy skills within the context of societal issues. Emphasis is placed on the NGSS science and engineering practices including: defining problems, carrying out investigations, analyzing data, and developing arguments based on evidence. Some example units of study may include: Infectious Diseases, Environmental Issues, Ethics in Science and Technology, and Sustainable Energy. Students can earn physical or life science credit toward high school graduation for this course.", recommended: [], department: Department.science, type: CourseType.standard, grade: [1, 2, 3]),
    
    //MATH
    "2210P": Course(name: "Algebra 1", id: "2210P", description: "Algebra 1 is imperative for success in subsequent math courses, and transitions students from arithmetic to symbolic reasoning. The key content, which follows the Common Core State Standards for Algebra 1, involves understanding, writing, solving, and graphing linear, exponential, and quadratic equations and inequalities. When working with linear equations, emphasis will be placed on understanding equations in slope-intercept form and slope in general as it relates to rates in context. Solving systems of two linear equations in two unknowns is also emphasized. Exponential relationships are studied in comparison with linear relationships to highlight the characteristics of exponential growth and decay. Quadratic equations are solved by factoring, using graphs, and applying the quadratic formula. Students should also become comfortable with operations on monomial and polynomial expressions. Students learn to solve problems employing all of these techniques. Successful completion of Algebra 1 prepares students for Geometry.", recommended: [], department: Department.math, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "2230P": Course(name: "Geometry", id: "2230P", description: "Recommended: Successful completion of Algebra 1. The Geometry course, which follows the Common Core State Standards for Geometry, focuses on a formal development of geometric skills and concepts. Students build their visualization, reasoning, and mathematical communication skills through study of the following topics: transformations, congruence, similarity, properties of geometric shapes (triangles, quadrilaterals, circles), geometric modeling (plane and solid), coordinate geometry, and right triangle trigonometry. They also develop the ability to construct formal logical arguments and proofs in a geometric setting. Geometry meets the graduation requirement, and together with Algebra 1, prepares a student for Algebra 2.", recommended: ["2210P"], department: Department.math, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "2310P": Course(name: "Algebra 2", id: "2310P", description: "Recommended: Successful completion of Algebra 1 and Geometry. Algebra 2 expands and refines the mathematical content of Algebra 1 and Geometry. Emphasis is placed on abstract thinking skills, the function concept, extension of right triangle trigonometry to the unit circle and domain of all real numbers, and the algebraic solution of problems in various content areas. Polynomial, exponential, logarithmic, radical, rational, and trigonometric functions comprise the core material through which equations, graphs, and their transformations are studied and applied. The course also includes an introduction to statistics and sequences and series. Calculators are used to aid in the solution of problems and in making estimates for realistic solutions. Successful completion of Algebra 2 prepares students for Pre-Calculus, Math Analysis or Applications of Advanced Mathematics.", recommended: ["2210P", "2230P"], department: Department.math, type: CourseType.standard,  grade: [0, 1, 2, 3]),
    "2320P": Course(name: "Alg 2/Trignometry", id: "2320P", description: "Recommended: Mastery of Algebra 1 and Geometry/Geometry Enriched. Algebra 2/Trigonometry is for students who plan to maximize the amount of mathematics studied in high school. Course content includes a more rigorous study of all topics taught in the Algebra 2 course. As in Algebra 2, emphasis is placed on abstract thinking skills, the function concept, extension of right triangle trigonometry to the unit circle and domain of all real numbers, and the algebraic solution of problems in various content areas. Polynomial, exponential, logarithmic, radical, rational, and trigonometric functions comprise the core material through which equations, graphs, and their transformations are studied and applied. The course also includes an introduction to statistics and sequences and series. Beyond the content of Algebra 2, in the trigonometry portion of Algebra 2 / Trigonometry, students study, in depth, all 6 trigonometric functions as they relate to the unit circle using radians and degrees, including simplifying expressions, solving equations, graphing, and applications. Additional topics include solving triangles, defining and solving equations with inverse trigonometric functions, and proving and applying trigonometric identities. Calculators are used to aid in the solution of problems and in making estimates for realistic solutions. Successful completion of Algebra 2/Trigonometry prepares students for Math Analysis or Applications of Advanced Mathematics. Mastery of Algebra 2/Trigonometry prepares students for Pre-Calculus Honors.", recommended: ["2210P", "2230P"], department: Department.math, type: CourseType.standard,  grade: [0, 1, 2, 3]),
    "2390P": Course(name: "Pre-Calculus", id: "2390P", description: "Recommended: Successful completion of Algebra 2/2-Trigonometry. Math Analysis focuses on the study of families of functions, their application in mathematical modeling, and the use of equivalence to rewrite expressions to reveal important features. Students analyze features of a variety of functions and their graphs, connect different representations, and identify and apply transformations of equations and graphs. To solve problems using function models, students choose among function families, fit linear and nonlinear functions to data, and interpret, apply, and evaluate the resulting models. The study of functions in this course includes strengthening of concepts and skills from prior courses, fuller development of equivalent forms of functions, and an in-depth study of trigonometry and its applications. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment. Full mastery of concepts and skills from this course prepares students to take Calculus AB the following year.", recommended: ["2310P", "2320P"], department: Department.math, type: CourseType.standard,  grade: [0, 1, 2, 3]),
    "2420H": Course(name: "Pre-Calculus Honors", id: "2420H", description: "Recommended: Mastery of both Geometry/Geometry Enriched and Algebra 2/Trigonometry. Pre-Calculus Honors is for students who plan to maximize the amount of mathematics studied in high school. This fast-paced course assumes that students have already mastered all skills and concepts from prior courses. The focus is on expanding the study of functions to a broad variety of function types, with increased emphasis on  abstract thinking and formal proofs. Students analyze features of a variety of functions and their graphs, connect different representations, and identify and apply transformations of equations and graphs. Students also solve challenging problems using function models, where they choose among function families, fit linear and nonlinear functions to data, and interpret, apply, and evaluate the resulting models. This course continues the rigorous study of trigonometry begun in Algebra 2/Trigonometry, moving on to advanced equations, graphs, and proofs, including the study of vectors and polar coordinates. Students also continue their study of topics such as the algebra of polynomials and rationals, advanced inequalities, conic sections, and sequences and series. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment. Successful completion of this course prepares students to take Calculus AB, or with full mastery of concepts and skills, Calculus BC, the following year.", recommended: ["2310P", "2320P"], department: Department.math, type: CourseType.honors,  grade: [0, 1, 2, 3]),
    "2430AP": Course(name: "AP Calculus AB", id: "2430AP", description: "Recommended: Mastery of Math Analysis. This course covers the content of two quarters (more than one semester) of a college Calculus curriculum, focusing on the application of limits, differentiation and integration. Some techniques of integration and indeterminate forms for limits are also covered. Throughout the course, an emphasis is placed on symbolic, graphical, and numeric representations, as well as on clear communication of mathematical thinking. Students successfully completing this course are prepared to take the Calculus AB AP exam, which requires use of a graphing calculator. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment.", recommended: ["2390P", "2420H"], department: Department.math, type: CourseType.ap,  grade: [0, 1, 2, 3]),
    "2440AP": Course(name: "AP Calculus BC", id: "2440AP", description: "Recommended: Mastery of Pre-Calculus Honors. This course covers the content of three quarters (two semesters) of a college Calculus curriculum, focusing on applications of limits, differentiation and integration. Numerical approaches (such as Newton’s method, Simpson’s Rule, and Euler’s Method); various techniques of integration; indeterminate forms for limits; and Taylor series are also covered, as well as application of Calculus techniques to parametric and polar representations. Throughout the course, an emphasis is placed on symbolic, graphical and numeric representations, as well as on clear communication of mathematical thinking. Students successfully completing this course are prepared to take the Calculus BC AP Exam, which requires use of a graphing calculator. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment.", recommended: ["2420H"], department: Department.math, type: CourseType.ap,  grade: [0, 1, 2, 3]),
    "2460AP": Course(name: "AP Statistics", id: "2460AP", description: "Recommended: Successful completion of Algebra 2 or higher math course. This course covers the content of one semester of an introductory, non-Calculus-based, college curriculum in Statistics, which is often a requirement for college students majoring in the social sciences, health sciences and business. Students will be introduced to the major concepts and tools for collecting, analyzing, and drawing conclusions from data. The course is built around four main topics: exploring data, planning a study, probability as it relates to distribution of data, and inferential reasoning. With the possible exception of probability, most of the material in this course has not been a part of the traditional secondary mathematics curriculum. Students successfully completing this course are prepared to take the Statistics AP Exam which includes use of a graphing calculator. Completion of this course with a grade of “C” or higher will clear a CSU Early Assessment Program result of “Conditionally Ready” on the 11th grade Smarter Balanced assessment.", recommended: ["2310P", "2320P", "2390P", "2420H", "2430AP", "2440AP"], department: Department.math, type: CourseType.ap,  grade: [1, 2, 3]),
    
    "2370P": Course(name: "Comp Prog Java", id: "2370P", description: "Recommended: Successful completion of Algebra 1 or higher math course and previous computer use. The course is designed to introduce the student to the study and writing of computer programs, with an emphasis on problem-solving and program design. Analytical thinking skills and logic are emphasized. The Java language is used with an emphasis on understanding universal programming concepts such as data types and data structures, selection, and iteration along with applications of programming for the Internet and programs written in an object-oriented paradigm. Elementary study of digital computer hardware may be included. This course is recommended for the college-bound student planning on a business, math or science major or for the student preparing for an AP Computer Science course.", recommended: [], department: Department.math, type: CourseType.standard,  grade: [0, 1, 2, 3]),
    "2350AP": Course(name: "AP Comp Sci A", id: "2350AP", description: "Recommended: Successful completion of Computer Programming Java and Algebra 2 or higher math course; This course is designed to serve as the equivalent of a one-semester, entry-level college course in computer science for students majoring in computer science, engineering, math, the sciences or business. Students are expected to have strong computer and problem-solving skills as they will create and debug original object-oriented programs, using Java, to solve problems by using adaptable and reusable algorithmic modules and data structures. Students successfully completing this course are prepared to take the AP Computer Science A Exam. This course may be used as 3rd year or beyond “c” requirement for “a” to “g” eligibility in addition to the successful completion of Algebra 2.", recommended: ["2370P"], department: Department.math, type: CourseType.ap,  grade: [1, 2, 3]),
    "7820AP": Course(name: "AP Comp Sci Principles", id: "7820AP", description: "The AP Computer Science Principles course is designed as the equivalent to a first-semester introductory college computing course. In this course, students will develop computational thinking skills vital for success across all disciplines, such as using computational tools to analyze and study data and working with large data sets to analyze, visualize, and draw conclusions from trends. The course is unique in its focus on fostering student creativity. Students are encouraged to apply creative processes when developing computational artifacts and to think creatively while using computer software and other technology to explore questions that interest them. They will also develop effective communication and collaboration skills, working individually and collaboratively to solve problems, and discussing and writing about the importance of these problems and the impacts to their community, society, and the world. Students complete part of the AP Computer Science Principles Exam through course assignments and activities, and take the other part of the exam in May. This course may be used as 3rdyear or beyond “d” requirement for “a” to “g” eligibility.", recommended: [], department: Department.math, type: CourseType.ap,  grade: [1, 2, 3]),
    
    
    //DRAMA
    "6710P": Course(name: "Drama", id: "6710P", description: "Recommended: None. This course is for those students who want introductory training in acting. Class emphasis is on voice, movement, improvisation, mental preparation, script preparation and various acting techniques. Course study may include the history of world theatre and theatre’s contributions to world cultures with representative readings of excellent plays from all cultures and eras; the formulation of criteria for personal evaluation of dramatic literature, performance and production; continued instruction in voice, staging and character analysis; playwriting techniques; directing techniques; rehearsal and performance for an audience.", recommended: [], department: Department.drama, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "6720P": Course(name: "Advanced Drama", id: "6720P", description: "Recommended: Drama. This course is for those students who want more advanced training in acting. Course work emphasizes reading, viewing, performing and analyzing dramatic works. Course study may include the history of world theatre and theatre’s contributions to world cultures with representative readings of excellent plays from all cultures and eras; the formulation of criteria for personal evaluation of dramatic literature, performance and production; continued instruction in voice, staging and character analysis; playwriting techniques; directing techniques; rehearsal and performance for an audience.", recommended: ["6710P"], department: Department.drama, type: CourseType.standard, grade: [1, 2, 3]),
    "6730H": Course(name: "Adv. Drama Honors", id: "6730H", description: "Recommended: Advanced Drama. This course is for those students who are most interested and practiced in studying acting and the theater. Course study will be based on the skills and knowledge developed in the previous Drama courses and will help students to continue on to more advanced levels of dramatic study. Students will be expected to have a solid foundation of dramatic principles and practices.", recommended: ["6720P"], department: Department.drama, type: CourseType.standard, grade: [2, 3]),
    
    //MUSIC
    "7030P": Course(name: "B Choir", id: "7030P", description: "Recommended: For students with little or no prior music experience. This choir is a beginning vocal group. It contains the basic introduction of the first year of high school vocal music. The techniques of vocal production and sight singing are explored. This choir performs for local school and community events.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "7040P": Course(name: "Adv. Treble Choir*", id: "7040P", description: "Audition only – see instructor for additional information. The course content includes work on tone production and quality, breathing, diction and general musicianship and the study and performance of three and four-part music for treble voices. This choir performs for local school and community events.", recommended: [], department: Department.music, type: CourseType.standard, grade: [1, 2, 3]),
    "7060P": Course(name: "A Choir*", id: "7060P", description: "Recommended: Audition or approval of instructor. The students will experience a large mixed choir that provides the opportunity to perform large choral works. This choir performs for local school and community events.", recommended: [], department: Department.music, type: CourseType.standard, grade: [1, 2, 3]),
    "7120P": Course(name: "Concert Band", id: "7120P", description: "Recommended: Approval of instructor. Refinement of tone and a more advanced understanding of basic performance techniques are stressed. The intonation, balance and blend required in ensemble playing are developed. Transposition and elementary music theory as related to band work are introduced; terms concerning tempo, dynamics and expression are emphasized through the reading of many compositions of different styles and from different periods in music history. The concert band performs concerts.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1]),
    "7130P": Course(name: "Symphonic Band", id: "7130P", description: "Recommended: Audition or approval of instructor. This is a continuation of Concert Band work, with more detail in individual techniques and skills. It provides continued study of band literature, with stress on a larger and more challenging repertoire. The symphonic band performs concerts.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "7140P": Course(name: "Wind Ensemble*", id: "7140P", description: "Recommended: Audition or approval of instructor. This select group of about 50 is formed by audition only. It is for the serious, advanced musician only, and performs more difficult high school and some college-level music. The wind ensemble performs concerts.", recommended: [], department: Department.music, type: CourseType.standard, grade: [1, 2, 3]),
    "7240P": Course(name: "Orchestra", id: "7240P", description: "Recommended: 1 – 2 years of prior experience. The course content involves the study and performance of ensemble and orchestra literature, intermediate and advanced string technique and musicianship.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "7250P": Course(name: "Chamber Orchestra", id: "7250P", description: "Audition required. This course is offered to advanced level students who will study and perform string/orchestral literature for continuing individual technique development on his/her instrument. Advanced/professional level music will be studied and performed from all historical periods of music. An emphasis is placed on Chamber music.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "7320P": Course(name: "Music Genesis", id: "7320P", description: "This course is open to all students interested in the basic elements and concepts of music through the study of Rock, Jazz and Classical music. No previous musical knowledge is required.", recommended: [], department: Department.music, type: CourseType.standard, grade: [0, 1, 2, 3]),
    
    //WL
    
    "4310P": Course(name: "Spanish 1", id: "4310P", description: "Recommended: None. Students will learn to address elements of daily life in both oral and written form, gain a new perspective on the world as they are introduced to other cultures and traditions, and learn the fundamental grammatical structures of the language to convey meaning. Class activities will allow students to become proficient in reading, writing, listening and speaking the target language for real-world language use.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4320P": Course(name: "Spanish 2", id: "4320P", description: "Recommended: C or better in Level 1, or language skills check. The primary goal continues to be the development of communicative competence. Students will use the target language to reinforce and expand their knowledge and to acquire new information about the target language and culture. They continue to build their language skills through more advanced reading, writing, speaking, and listening activities.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4330P": Course(name: "Spanish 3", id: "4330P", description: "Recommended: C or better in Level 2, or language skills check. Students will learn more advanced vocabulary and grammar, and will improve communicative competence in the target language. More formal writing skills begin to be developed. Cultural study promotes a deeper understanding of the people who speak the language. They will begin to develop the ability to understand the language spoken at the pace of a native speaker. The course will be conducted primarily in the target language.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4340H": Course(name: "Spanish 4 - Honors", id: "4340H", description: "Recommended: C or better in Level 3, or language skills check. The course includes advanced grammar and vocabulary. The goal will continue to be communicative competence, with an emphasis on understanding and using more complex and precise language. The students read and respond to a variety of texts in the target language to reinforce and expand their language skills. There is a focus on writing well-structured responses to a variety of prompts. The study of culture continues to be an integral part of the course. Level 4 Honors is conducted entirely in the target language.", recommended: [], department: Department.wl, type: CourseType.honors, grade: [0, 1, 2, 3]),
    "4350AP": Course(name: "AP Spanish Lang/Culture", id: "4350AP", description: "Recommended: C or better in Level 4 Honors, or language skills check. The Advanced Placement course aims to develop overall fluency in the language. Students will continue to expand and refine their skills with college level coursework. The course prepares students to demonstrate their advanced level of proficiency across three communicative modes: interpersonal (interactive communication), interpretive (receptive communication) and presentational (productive communication). Students will hone their ability to respond to written material, both fiction and non-fiction. One of the goals of the course is to prepare students for the AP Language Exam. A student may receive college credit by earning a passing grade on this national exam.", recommended: [], department: Department.wl, type: CourseType.ap, grade: [0, 1, 2, 3]),

    
    "4110P": Course(name: "French 1", id: "4110P", description: "Recommended: None. Students will learn to address elements of daily life in both oral and written form, gain a new perspective on the world as they are introduced to other cultures and traditions, and learn the fundamental grammatical structures of the language to convey meaning. Class activities will allow students to become proficient in reading, writing, listening and speaking the target language for real-world language use.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4120P": Course(name: "French 2", id: "4120P", description: "Recommended: C or better in Level 1, or language skills check. The primary goal continues to be the development of communicative competence. Students will use the target language to reinforce and expand their knowledge and to acquire new information about the target language and culture. They continue to build their language skills through more advanced reading, writing, speaking, and listening activities.", recommended: ["4110P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4130P": Course(name: "French 3", id: "4130P", description: "Recommended: C or better in Level 2, or language skills check. Students will learn more advanced vocabulary and grammar, and will improve communicative competence in the target language. More formal writing skills begin to be developed. Cultural study promotes a deeper understanding of the people who speak the language. They will begin to develop the ability to understand the language spoken at the pace of a native speaker. The course will be conducted primarily in the target language.", recommended: ["4120P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4140H": Course(name: "French 4 - Honors", id: "4140H", description: "Recommended: C or better in Level 3, or language skills check. The course includes advanced grammar and vocabulary. The goal will continue to be communicative competence, with an emphasis on understanding and using more complex and precise language. The students read and respond to a variety of texts in the target language to reinforce and expand their language skills. There is a focus on writing well-structured responses to a variety of prompts. The study of culture continues to be an integral part of the course. Level 4 Honors is conducted entirely in the target language.", recommended: ["4130P"], department: Department.wl, type: CourseType.honors, grade: [0, 1, 2, 3]),
    "4150AP": Course(name: "AP French Lang/Culture", id: "4150AP", description: "ecommended: C or better in Level 4 Honors, or language skills check. The Advanced Placement course aims to develop overall fluency in the language. Students will continue to expand and refine their skills with college level coursework. The course prepares students to demonstrate their advanced level of proficiency across three communicative modes: interpersonal (interactive communication), interpretive (receptive communication) and presentational (productive communication). Students will hone their ability to respond to written material, both fiction and non-fiction. One of the goals of the course is to prepare students for the AP Language Exam. A student may receive college credit by earning a passing grade on this national exam.", recommended: ["4140H"], department: Department.wl, type: CourseType.ap, grade: [0, 1, 2, 3]),
    
    "4010P": Course(name: "Japanese 1", id: "4010P", description: "Recommended: None. Students will learn to address elements of daily life in both oral and written form, gain a new perspective on the world as they are introduced to other cultures and traditions, and learn the fundamental grammatical structures of the language to convey meaning. Class activities will allow students to become proficient in reading, writing, listening and speaking the target language for real-world language use.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4020P": Course(name: "Japanese 2", id: "4020P", description: "Recommended: C or better in Level 1, or language skills check. The primary goal continues to be the development of communicative competence. Students will use the target language to reinforce and expand their knowledge and to acquire new information about the target language and culture. They continue to build their language skills through more advanced reading, writing, speaking, and listening activities.", recommended: ["4010P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4030P": Course(name: "Japanese 3", id: "4030P", description: "Recommended: C or better in Level 2, or language skills check. Students will learn more advanced vocabulary and grammar, and will improve communicative competence in the target language. More formal writing skills begin to be developed. Cultural study promotes a deeper understanding of the people who speak the language. They will begin to develop the ability to understand the language spoken at the pace of a native speaker. The course will be conducted primarily in the target language.", recommended: ["4020P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4040H": Course(name: "Japanese 4 - Honors", id: "4040H", description: "Recommended: C or better in Level 3, or language skills check. The course includes advanced grammar and vocabulary. The goal will continue to be communicative competence, with an emphasis on understanding and using more complex and precise language. The students read and respond to a variety of texts in the target language to reinforce and expand their language skills. There is a focus on writing well-structured responses to a variety of prompts. The study of culture continues to be an integral part of the course. Level 4 Honors is conducted entirely in the target language.", recommended: ["4030P"], department: Department.wl, type: CourseType.honors, grade: [0, 1, 2, 3]),
    "4050AP": Course(name: "AP Japanese Lang/Culture", id: "4050AP", description: "ecommended: C or better in Level 4 Honors, or language skills check. The Advanced Placement course aims to develop overall fluency in the language. Students will continue to expand and refine their skills with college level coursework. The course prepares students to demonstrate their advanced level of proficiency across three communicative modes: interpersonal (interactive communication), interpretive (receptive communication) and presentational (productive communication). Students will hone their ability to respond to written material, both fiction and non-fiction. One of the goals of the course is to prepare students for the AP Language Exam. A student may receive college credit by earning a passing grade on this national exam.", recommended: ["4040H"], department: Department.wl, type: CourseType.ap, grade: [0, 1, 2, 3]),
    
    "4410P": Course(name: "Chinese 1", id: "4410P", description: "Recommended: None. Students will learn to address elements of daily life in both oral and written form, gain a new perspective on the world as they are introduced to other cultures and traditions, and learn the fundamental grammatical structures of the language to convey meaning. Class activities will allow students to become proficient in reading, writing, listening and speaking the target language for real-world language use.", recommended: [], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4420P": Course(name: "Chinese 2", id: "4420P", description: "Recommended: C or better in Level 1, or language skills check. The primary goal continues to be the development of communicative competence. Students will use the target language to reinforce and expand their knowledge and to acquire new information about the target language and culture. They continue to build their language skills through more advanced reading, writing, speaking, and listening activities.", recommended: ["4410P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4430P": Course(name: "Chinese 3", id: "4430P", description: "Recommended: C or better in Level 2, or language skills check. Students will learn more advanced vocabulary and grammar, and will improve communicative competence in the target language. More formal writing skills begin to be developed. Cultural study promotes a deeper understanding of the people who speak the language. They will begin to develop the ability to understand the language spoken at the pace of a native speaker. The course will be conducted primarily in the target language.", recommended: ["4420P"], department: Department.wl, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4440H": Course(name: "Chinese 4 - Honors", id: "4440H", description: "Recommended: C or better in Level 3, or language skills check. The course includes advanced grammar and vocabulary. The goal will continue to be communicative competence, with an emphasis on understanding and using more complex and precise language. The students read and respond to a variety of texts in the target language to reinforce and expand their language skills. There is a focus on writing well-structured responses to a variety of prompts. The study of culture continues to be an integral part of the course. Level 4 Honors is conducted entirely in the target language.", recommended: ["4430P"], department: Department.wl, type: CourseType.honors, grade: [0, 1, 2, 3]),
    "4450AP": Course(name: "AP Chinese Lang/Culture", id: "4450AP", description: "ecommended: C or better in Level 4 Honors, or language skills check. The Advanced Placement course aims to develop overall fluency in the language. Students will continue to expand and refine their skills with college level coursework. The course prepares students to demonstrate their advanced level of proficiency across three communicative modes: interpersonal (interactive communication), interpretive (receptive communication) and presentational (productive communication). Students will hone their ability to respond to written material, both fiction and non-fiction. One of the goals of the course is to prepare students for the AP Language Exam. A student may receive college credit by earning a passing grade on this national exam.", recommended: ["4440H"], department: Department.wl, type: CourseType.ap, grade: [0, 1, 2, 3]),
    
    
    //BUSINESS
    "4580P": Course(name: "Principle of Business", id: "4580P", description: "This business course introduces students to the study of Economics, Personal Finance, Commerce, and Entrepreneurship. Course projects focus on applying economic concepts, financial literacy, investments in the stock market, sales and marketing strategies, career exploration, and creating a business plan. This course sets the foundation is ideal for students seeking financial freedom and a foundation for success in any career.", recommended: [], department: Department.business, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "4710P": Course(name: "Accounting 1", id: "4710P", description: "Accounting 1 will enable the students to understand the 'language' of business, the recording of financial transactions and their interpretation, the clarification of business procedures, the provision of skills needed for keeping financial records, practice in setting up accounting systems and preparation of income statements and balance sheets. Students will also learn how to invest in opportunities such as stocks, bonds, real estate, and mutual funds. Computerized accounting and an introduction to taxes are also included in the curriculum. The course is recommended for students who plan to enter college and major or minor in this industry sector including business administration, accounting, marketing, international business management.", recommended: [], department: Department.business, type: CourseType.standard, grade: [1, 2, 3]),
    "4720P": Course(name: "Accounting 2", id: "4720P", description: "Required: Accounting 1. This advanced course is designed for students who want to broaden and improve knowledge about business procedures and the use of accounting records. Students that complete this class usually go on to college and major in accounting or some other phase of business. Priority will be given to students who are progressing in the Design, Financial Services Pathway and choose this as one of their “First 6” classes.", recommended: ["4710P"], department: Department.business, type: CourseType.standard, grade: [1, 2, 3]),
    "4880P": Course(name: "Econ & Virtual Bus", id: "4880P", description: "Recommended: Principles of Business. Virtual Enterprise (VE) is a simulated business that is set up and run by students. With the guidance of the teacher and real-world business partners, students will determine the nature of their business, its products and services, its management and structures and learn the daily operation of a business. They will participate in simulated on-the-job work experiences, including accounting, personnel administration, management and marketing. Emphasis is placed on using current business software and communication tools for business transactions. Students will run their own virtual checking account, receive a virtual paycheck, and pay virtual bills including rent, utilities and miscellaneous expenditures. They will be responsible for having a grand opening for their business and will have the opportunity to attend one of two (or more) trade fairs. Working collaboratively, students will develop and enhance oral and written communication skills through initiative, creativity and responsibility. All class experiences simulate those found in business and industry. Priority will be given to students who are progressing in the Business Management Pathway and choose this as one of their “First 6” classes.", recommended: ["4580P"], department: Department.business, type: CourseType.standard, grade: [1, 2, 3]),
    
    //LIVING SKILLS
    "5710": Course(name: "Culinary Arts 1", id: "5710", description: "This is a preparatory course addressing many aspects of food preparation including safety and sanitation, measurement basics, kitchen tools and uses, nutrition, basic food science, and meal planning and preparation. The goal of this course is to introduce the kitchen novice to the wonderful world of food and flavors. Students also will explore the array of careers in the food industry.", recommended: [], department: Department.living, type: CourseType.standard, grade: [0, 1, 2, 3]),
    "5730P": Course(name: "Culinary Food Science", id: "5730P", description: "Recommended: Passing grade in Biology and Algebra 1. This course applies chemistry, biology, and basic scientific principles in analyzing the processing of food and food products, the preparation of recipes along with concepts of food preservation, the packaging and marketing of foods as well as discussions about scientific advances or consumer demands and the resulting affects on world food issues. The course takes a hands-on approach to learning through the preparation of foods by understanding the “how” and “why” of a recipe, and develops a student’s knowledge of the role of food in respect to its nutritional, social, historical, environmental and industrial contexts using research, reasoning, and prior knowledge. In accordance with the standards of Career Technical Education, the students will also learn about nutrition, sensory evaluation, and the safe handling of food through the use of written lab reports and kitchen lab experiments. Priority will be given to students who are progressing in the Hospitality Pathway and choose this as one of their “First 6” classes.", recommended: ["3110P"], department: Department.living, type: CourseType.standard, grade: [1, 2, 3]),
    
    //NON-DEPARTMENTAL
    "8040": Course(name: "Work Experience", id: "8040", description: "Students who are employed may choose to enroll in Work Experience with priority given to seniors who need credits toward graduation or need to work. Throughout their time in the program, students develop and complete a portfolio, which demonstrates research about multiple career paths alongside the abilities, knowledge, and skills gained through Work Experience. Credit is granted quarterly, and is based on a combination of completion of related instruction, attendance at class meetings, employer/teacher evaluations, and hours of employment. Students interested in this course should contact their School Counselor.", recommended: [], department: Department.misc, type: CourseType.other, grade: [2, 3]),
    "8280": Course(name: "IS: STEM Research", id: "8280", description: "STEAM research course is a unique opportunity for students to engage in interdisciplinary research to understand complex problems including equity issues, and take action to make a positive change in their community. Students will explore equity focused topics in a wide variety of disciplines including humanities and social sciences, sports, performing arts, science, engineering and technology. This research course will help students in developing unique skills in thinking like a researcher. Students are expected to have their own research project and spend about 60 hours per semester (3-4 hours per week) on their project. The year-long course is a 10 unit, non-UC elective course that will be graded pass/fail. It can be taken concurrently with another science course.", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1]),
    "8290": Course(name: "Leadership*", id: "8040", description: "Required: Students must hold some type of office through elections or interviews. Leadership is a “How To” course where traditional and nontraditional student leaders and potential student leaders will develop skills that will be utilized in planning and presenting schoolwide activities and programs. Community involvement will be expected via activities in the elementary schools such as conflict resolution, peer tutoring, performances, or presentations, as well as attendance at local government meetings and assistance with community programs such as food drives and multicultural activities. Other examples of activities may include but are not limited to: rallies, lunch-time activities, dances, student and staff recognition, homecoming, Students will be active participants in planning and presenting the course and their work will be assessed through actual presentations and portfolio development. This course is open to all students and is repeatable.", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1, 2, 3]),
    "8390": Course(name: "Engage*", id: "8390", description: "", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1, 2, 3]),
    "8400": Course(name: "Engage Tutor*", id: "8400", description: "Recommended: Permission of supervising teacher/staff and completion of tutor training workshop if offered. This course is designed to provide an opportunity for students to give school service by tutoring special needs students during a regularly scheduled class or students in the regular program who only need academic assistance. Students are also expected to give time to tutoring outside of the regularly scheduled class. Students have the opportunity to learn about different learning styles, to value diversity, to give service and to explore teaching as a career.", recommended: [], department: Department.misc, type: CourseType.other, grade: [2, 3]),
    "9020": Course(name: "TA/Student Clerk", id: "9020", description: "Recommended: Approval from staff member whom the assistant/clerk will be supporting. Students enrolled in these courses will work with administrators, teachers and clerical staff to support the cafeteria, library, front office, and/or general campus. Students enrolled in these courses will receive work simulation experiences. Students will receive a letter grade for this course. Students may earn a maximum of 20 credits in these classes during their 4 years of high school.", recommended: [], department: Department.misc, type: CourseType.other, grade: [1, 2, 3]),
    "9030": Course(name: "EL Teacher Asst", id: "9030", description: "Recommended: Approval from staff member who the assistant will be supporting. Students enrolled in these courses will work with teachers and clerical staff to support the classroom and overall academic environment. Students can be expected to fulfill a variety of requests from the staff to set up and support the academic needs of the classroom. Students enrolled in these courses will receive work simulation experiences. Students will receive a letter grade for this course. Students may earn a maximum of 20 credits in these classes during their 4 years of high school.", recommended: [], department: Department.misc, type: CourseType.other, grade: [2, 3]),
    "9070": Course(name: "Technology Asst", id: "9070", description: "Recommended: Approval from staff member whom the assistant/clerk will be supporting. Students enrolled in these courses will work with administrators, teachers and clerical staff to support the cafeteria, library, front office, and/or general campus. Students enrolled in these courses will receive work simulation experiences. Students will receive a letter grade for this course. Students may earn a maximum of 20 credits in these classes during their 4 years of high school.", recommended: [], department: Department.misc, type: CourseType.other, grade: [1, 2, 3]),
    "8380": Course(name: "Yearbook", id: "8380", description: "", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1, 2, 3]),
    "1595": Course(name: "Intro to Ethnic Studies (1/2)", id: "1595", description: "Introduction to Ethnic Studies is a 9th grade, one semester course. Students should expect to examine the complexities of identity - their own and others’ - to develop awareness of personal and community connections to local and global histories and to foster empathy. This awareness and empathy will be developed by studying the narratives of and by people from historically marginalized groups in order to understand the ways that individuals and communities shape and are shaped by institutions and cultures. The course is built on the foundational principles that: (1) every student brings valuable knowledge, experience, and ideas with them into the classroom, (2) students have power to transform society, and (3) while everyone has different needs, everyone’s well-being is interconnected. Course materials and overarching questions will emphasize the intersections of identity including, but not limited to: race, religion, gender, (dis)ability, and immigrant status, etc. Lessons will be interdisciplinary, drawing from history, literature, art, and other subjects. Students will explicitly be taught skills that will help them to be successful in future classes including perspective-taking, developing questions, analyzing multiple - sometimes conflicting - sources, creative problem solving, and communicating & collaborating with others.", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1]),
    "3025": Course(name: "Health (2/2)", id: "3025", description: "Recommended: Approval from staff member who the assistant will be supporting. Students enrolled in these courses will work with teachers and clerical staff to support the classroom and overall academic environment. Students can be expected to fulfill a variety of requests from the staff to set up and support the academic needs of the classroom. Students enrolled in these courses will receive work simulation experiences. Students will receive a letter grade for this course. Students may earn a maximum of 20 credits in these classes during their 4 years of high school.", recommended: [], department: Department.misc, type: CourseType.other, grade: [0, 1])
    
    
]

class CoursePlannerViewModel: ObservableObject {
    @Published var schedule: Schedule = Schedule()
}

typealias CourseIdentifier = String

enum CourseType {
    case standard
    case honors
    case ap
    case other
}

enum Department: Comparable {
    case english
    case social
    case pe
    case art
    case science
    case math
    case drama
    case music
    case wl
    case business
    case living
    case misc
    
    case zero
}

class Course: Identifiable {
    let name: String
    let id: CourseIdentifier
    let description: String
    let recommended: [String]
    let department: Department
    let type: CourseType
    let grade: [Int]
    
    init(name: String, id: CourseIdentifier, description: String, recommended: [CourseIdentifier], department: Department, type: CourseType, grade: [Int]) {
        self.name = name
        self.id = id
        self.description = description
        self.recommended = recommended
        self.department = department
        self.type = type
        self.grade = grade
    }
    
    
}

extension Course: Comparable {
    static func < (lhs: Course, rhs: Course) -> Bool {
        return lhs.department < rhs.department
    }
    
    static func == (lhs: Course, rhs: Course) -> Bool {
        return lhs.department == rhs.department
    }
}

class Schedule: Identifiable, Codable {
    var years: [[CourseIdentifier]] = [
        ["1010P", "0000", "3110P", "0000", "0000", "0000", "2510"],
        ["1020P", "1620P", "0000", "0000", "0000", "0000", "0000"],
        ["0000", "0000", "0000", "0000", "0000", "0000", "0000"],
        ["0000", "1835P", "0000", "0000", "0000", "0000", "0000"]
    ]
    
    init() { }
    
}
